name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

# Set permissions needed for GitHub Pages deployment
permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci # Use npm ci for clean installation

      - name: Clean build directory
        run: rm -rf dist || true
        
      - name: Build project
        run: npm run build
        
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist # Change this if your build output directory is different
          branch: gh-pages
          clean: true # This ensures old files are removed
          token: ${{ github.token }} # Explicitly use the GitHub token
